/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PamTokenRouteImport } from './routes/pam.$token'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiBaseRouteImport } from './routes/api/base'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos.index'
import { Route as AvaliacaoDesempenhoPreencherTokenRouteImport } from './routes/avaliacao-desempenho.preencher.$token'
import { Route as AtividadesPreencherTokenRouteImport } from './routes/atividades.preencher.$token'
import { Route as ApiProjectsProjectIdRouteImport } from './routes/api/projects.$projectId'
import { Route as ApiBaseSectionsRouteImport } from './routes/api/base.sections'
import { Route as ApiBaseOptionsRouteImport } from './routes/api/base.options'
import { Route as ApiBaseFieldsRouteImport } from './routes/api/base.fields'
import { Route as ApiBaseAccessRouteImport } from './routes/api/base.access'
import { Route as AuthenticatedProjetosNovoRouteImport } from './routes/_authenticated/projetos.novo'
import { Route as AuthenticatedProjetosProjectIdRouteImport } from './routes/_authenticated/projetos.$projectId'
import { Route as AuthenticatedGerenciamentoUsuariosRouteImport } from './routes/_authenticated/gerenciamento.usuarios'
import { Route as AuthenticatedGerenciamentoBasesRouteImport } from './routes/_authenticated/gerenciamento.bases'
import { Route as AuthenticatedGerenciamentoAtrelarRouteImport } from './routes/_authenticated/gerenciamento.atrelar'
import { Route as AuthenticatedProjetosProjectIdIndexRouteImport } from './routes/_authenticated/projetos.$projectId.index'
import { Route as AuthenticatedGerenciamentoUsuariosIndexRouteImport } from './routes/_authenticated/gerenciamento.usuarios.index'
import { Route as ApiPublicPerformanceResponseTokenRouteImport } from './routes/api/public/performance-response.$token'
import { Route as ApiPublicPerformanceFormTokenRouteImport } from './routes/api/public/performance-form.$token'
import { Route as ApiPublicPerformanceDraftTokenRouteImport } from './routes/api/public/performance-draft.$token'
import { Route as ApiPublicPamTokenRouteImport } from './routes/api/public/pam.$token'
import { Route as ApiPublicPamDraftTokenRouteImport } from './routes/api/public/pam-draft.$token'
import { Route as ApiPublicPamCompleteTokenRouteImport } from './routes/api/public/pam-complete.$token'
import { Route as ApiPublicActivityResponseTokenRouteImport } from './routes/api/public/activity-response.$token'
import { Route as ApiPublicActivityFormTokenRouteImport } from './routes/api/public/activity-form.$token'
import { Route as ApiPublicActivityDraftTokenRouteImport } from './routes/api/public/activity-draft.$token'
import { Route as ApiProjectsProjectIdAreasRouteImport } from './routes/api/projects.$projectId.areas'
import { Route as ApiBaseOptionsOptionIdRouteImport } from './routes/api/base.options.$optionId'
import { Route as ApiBaseFieldsOrderRouteImport } from './routes/api/base.fields.order'
import { Route as ApiBaseFieldsFieldIdRouteImport } from './routes/api/base.fields.$fieldId'
import { Route as AuthenticatedProjetosProjectIdPamRouteImport } from './routes/_authenticated/projetos.$projectId.pam'
import { Route as AuthenticatedProjetosProjectIdOrganogramaRouteImport } from './routes/_authenticated/projetos.$projectId.organograma'
import { Route as AuthenticatedProjetosProjectIdHistoricoRouteImport } from './routes/_authenticated/projetos.$projectId.historico'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo'
import { Route as AuthenticatedProjetosProjectIdConfiguracoesRouteImport } from './routes/_authenticated/projetos.$projectId.configuracoes'
import { Route as AuthenticatedProjetosProjectIdColaboradoresRouteImport } from './routes/_authenticated/projetos.$projectId.colaboradores'
import { Route as AuthenticatedProjetosProjectIdBaseRouteImport } from './routes/_authenticated/projetos.$projectId.base'
import { Route as AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteImport } from './routes/_authenticated/projetos.$projectId.avaliacao-desempenho'
import { Route as AuthenticatedProjetosProjectIdAtividadesRouteImport } from './routes/_authenticated/projetos.$projectId.atividades'
import { Route as AuthenticatedProjetosProjectIdAreasRouteImport } from './routes/_authenticated/projetos.$projectId.areas'
import { Route as AuthenticatedProjetosProjectIdAndamentoRouteImport } from './routes/_authenticated/projetos.$projectId.andamento'
import { Route as AuthenticatedGerenciamentoUsuariosNovoRouteImport } from './routes/_authenticated/gerenciamento.usuarios.novo'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoIndexRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo.index'
import { Route as ApiProjectsProjectIdAreasAreaIdRouteImport } from './routes/api/projects.$projectId.areas.$areaId'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoNovoRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo.novo'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoDcIdRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo.$dcId'
import { Route as AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRouteImport } from './routes/_authenticated/projetos.$projectId.avaliacao-desempenho.comparar.$reviewId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PamTokenRoute = PamTokenRouteImport.update({
  id: '/pam/$token',
  path: '/pam/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaseRoute = ApiBaseRouteImport.update({
  id: '/api/base',
  path: '/api/base',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AvaliacaoDesempenhoPreencherTokenRoute =
  AvaliacaoDesempenhoPreencherTokenRouteImport.update({
    id: '/avaliacao-desempenho/preencher/$token',
    path: '/avaliacao-desempenho/preencher/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtividadesPreencherTokenRoute =
  AtividadesPreencherTokenRouteImport.update({
    id: '/atividades/preencher/$token',
    path: '/atividades/preencher/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdRoute = ApiProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ApiProjectsRoute,
} as any)
const ApiBaseSectionsRoute = ApiBaseSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => ApiBaseRoute,
} as any)
const ApiBaseOptionsRoute = ApiBaseOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => ApiBaseRoute,
} as any)
const ApiBaseFieldsRoute = ApiBaseFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => ApiBaseRoute,
} as any)
const ApiBaseAccessRoute = ApiBaseAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => ApiBaseRoute,
} as any)
const AuthenticatedProjetosNovoRoute =
  AuthenticatedProjetosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AuthenticatedProjetosProjectIdRoute =
  AuthenticatedProjetosProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AuthenticatedGerenciamentoUsuariosRoute =
  AuthenticatedGerenciamentoUsuariosRouteImport.update({
    id: '/gerenciamento/usuarios',
    path: '/gerenciamento/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGerenciamentoBasesRoute =
  AuthenticatedGerenciamentoBasesRouteImport.update({
    id: '/gerenciamento/bases',
    path: '/gerenciamento/bases',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGerenciamentoAtrelarRoute =
  AuthenticatedGerenciamentoAtrelarRouteImport.update({
    id: '/gerenciamento/atrelar',
    path: '/gerenciamento/atrelar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetosProjectIdIndexRoute =
  AuthenticatedProjetosProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedGerenciamentoUsuariosIndexRoute =
  AuthenticatedGerenciamentoUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGerenciamentoUsuariosRoute,
  } as any)
const ApiPublicPerformanceResponseTokenRoute =
  ApiPublicPerformanceResponseTokenRouteImport.update({
    id: '/api/public/performance-response/$token',
    path: '/api/public/performance-response/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPerformanceFormTokenRoute =
  ApiPublicPerformanceFormTokenRouteImport.update({
    id: '/api/public/performance-form/$token',
    path: '/api/public/performance-form/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPerformanceDraftTokenRoute =
  ApiPublicPerformanceDraftTokenRouteImport.update({
    id: '/api/public/performance-draft/$token',
    path: '/api/public/performance-draft/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPamTokenRoute = ApiPublicPamTokenRouteImport.update({
  id: '/api/public/pam/$token',
  path: '/api/public/pam/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPamDraftTokenRoute = ApiPublicPamDraftTokenRouteImport.update({
  id: '/api/public/pam-draft/$token',
  path: '/api/public/pam-draft/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPamCompleteTokenRoute =
  ApiPublicPamCompleteTokenRouteImport.update({
    id: '/api/public/pam-complete/$token',
    path: '/api/public/pam-complete/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivityResponseTokenRoute =
  ApiPublicActivityResponseTokenRouteImport.update({
    id: '/api/public/activity-response/$token',
    path: '/api/public/activity-response/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivityFormTokenRoute =
  ApiPublicActivityFormTokenRouteImport.update({
    id: '/api/public/activity-form/$token',
    path: '/api/public/activity-form/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivityDraftTokenRoute =
  ApiPublicActivityDraftTokenRouteImport.update({
    id: '/api/public/activity-draft/$token',
    path: '/api/public/activity-draft/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdAreasRoute =
  ApiProjectsProjectIdAreasRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () => ApiProjectsProjectIdRoute,
  } as any)
const ApiBaseOptionsOptionIdRoute = ApiBaseOptionsOptionIdRouteImport.update({
  id: '/$optionId',
  path: '/$optionId',
  getParentRoute: () => ApiBaseOptionsRoute,
} as any)
const ApiBaseFieldsOrderRoute = ApiBaseFieldsOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ApiBaseFieldsRoute,
} as any)
const ApiBaseFieldsFieldIdRoute = ApiBaseFieldsFieldIdRouteImport.update({
  id: '/$fieldId',
  path: '/$fieldId',
  getParentRoute: () => ApiBaseFieldsRoute,
} as any)
const AuthenticatedProjetosProjectIdPamRoute =
  AuthenticatedProjetosProjectIdPamRouteImport.update({
    id: '/pam',
    path: '/pam',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdOrganogramaRoute =
  AuthenticatedProjetosProjectIdOrganogramaRouteImport.update({
    id: '/organograma',
    path: '/organograma',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdHistoricoRoute =
  AuthenticatedProjetosProjectIdHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoRouteImport.update({
    id: '/descricao-cargo',
    path: '/descricao-cargo',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdConfiguracoesRoute =
  AuthenticatedProjetosProjectIdConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdColaboradoresRoute =
  AuthenticatedProjetosProjectIdColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdBaseRoute =
  AuthenticatedProjetosProjectIdBaseRouteImport.update({
    id: '/base',
    path: '/base',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute =
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteImport.update({
    id: '/avaliacao-desempenho',
    path: '/avaliacao-desempenho',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAtividadesRoute =
  AuthenticatedProjetosProjectIdAtividadesRouteImport.update({
    id: '/atividades',
    path: '/atividades',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAreasRoute =
  AuthenticatedProjetosProjectIdAreasRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAndamentoRoute =
  AuthenticatedProjetosProjectIdAndamentoRouteImport.update({
    id: '/andamento',
    path: '/andamento',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedGerenciamentoUsuariosNovoRoute =
  AuthenticatedGerenciamentoUsuariosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedGerenciamentoUsuariosRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosProjectIdDescricaoCargoRoute,
  } as any)
const ApiProjectsProjectIdAreasAreaIdRoute =
  ApiProjectsProjectIdAreasAreaIdRouteImport.update({
    id: '/$areaId',
    path: '/$areaId',
    getParentRoute: () => ApiProjectsProjectIdAreasRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProjetosProjectIdDescricaoCargoRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoDcIdRouteImport.update({
    id: '/$dcId',
    path: '/$dcId',
    getParentRoute: () => AuthenticatedProjetosProjectIdDescricaoCargoRoute,
  } as any)
const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute =
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRouteImport.update(
    {
      id: '/comparar/$reviewId',
      path: '/comparar/$reviewId',
      getParentRoute: () =>
        AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/api/base': typeof ApiBaseRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/pam/$token': typeof PamTokenRoute
  '/gerenciamento/atrelar': typeof AuthenticatedGerenciamentoAtrelarRoute
  '/gerenciamento/bases': typeof AuthenticatedGerenciamentoBasesRoute
  '/gerenciamento/usuarios': typeof AuthenticatedGerenciamentoUsuariosRouteWithChildren
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRouteWithChildren
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/api/base/access': typeof ApiBaseAccessRoute
  '/api/base/fields': typeof ApiBaseFieldsRouteWithChildren
  '/api/base/options': typeof ApiBaseOptionsRouteWithChildren
  '/api/base/sections': typeof ApiBaseSectionsRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/atividades/preencher/$token': typeof AtividadesPreencherTokenRoute
  '/avaliacao-desempenho/preencher/$token': typeof AvaliacaoDesempenhoPreencherTokenRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/gerenciamento/usuarios/novo': typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  '/projetos/$projectId/andamento': typeof AuthenticatedProjetosProjectIdAndamentoRoute
  '/projetos/$projectId/areas': typeof AuthenticatedProjetosProjectIdAreasRoute
  '/projetos/$projectId/atividades': typeof AuthenticatedProjetosProjectIdAtividadesRoute
  '/projetos/$projectId/avaliacao-desempenho': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  '/projetos/$projectId/base': typeof AuthenticatedProjetosProjectIdBaseRoute
  '/projetos/$projectId/colaboradores': typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  '/projetos/$projectId/configuracoes': typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  '/projetos/$projectId/descricao-cargo': typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren
  '/projetos/$projectId/historico': typeof AuthenticatedProjetosProjectIdHistoricoRoute
  '/projetos/$projectId/organograma': typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  '/projetos/$projectId/pam': typeof AuthenticatedProjetosProjectIdPamRoute
  '/api/base/fields/$fieldId': typeof ApiBaseFieldsFieldIdRoute
  '/api/base/fields/order': typeof ApiBaseFieldsOrderRoute
  '/api/base/options/$optionId': typeof ApiBaseOptionsOptionIdRoute
  '/api/projects/$projectId/areas': typeof ApiProjectsProjectIdAreasRouteWithChildren
  '/api/public/activity-draft/$token': typeof ApiPublicActivityDraftTokenRoute
  '/api/public/activity-form/$token': typeof ApiPublicActivityFormTokenRoute
  '/api/public/activity-response/$token': typeof ApiPublicActivityResponseTokenRoute
  '/api/public/pam-complete/$token': typeof ApiPublicPamCompleteTokenRoute
  '/api/public/pam-draft/$token': typeof ApiPublicPamDraftTokenRoute
  '/api/public/pam/$token': typeof ApiPublicPamTokenRoute
  '/api/public/performance-draft/$token': typeof ApiPublicPerformanceDraftTokenRoute
  '/api/public/performance-form/$token': typeof ApiPublicPerformanceFormTokenRoute
  '/api/public/performance-response/$token': typeof ApiPublicPerformanceResponseTokenRoute
  '/gerenciamento/usuarios/': typeof AuthenticatedGerenciamentoUsuariosIndexRoute
  '/projetos/$projectId/': typeof AuthenticatedProjetosProjectIdIndexRoute
  '/projetos/$projectId/descricao-cargo/$dcId': typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  '/projetos/$projectId/descricao-cargo/novo': typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  '/api/projects/$projectId/areas/$areaId': typeof ApiProjectsProjectIdAreasAreaIdRoute
  '/projetos/$projectId/descricao-cargo/': typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
  '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/api/base': typeof ApiBaseRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/pam/$token': typeof PamTokenRoute
  '/gerenciamento/atrelar': typeof AuthenticatedGerenciamentoAtrelarRoute
  '/gerenciamento/bases': typeof AuthenticatedGerenciamentoBasesRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/api/base/access': typeof ApiBaseAccessRoute
  '/api/base/fields': typeof ApiBaseFieldsRouteWithChildren
  '/api/base/options': typeof ApiBaseOptionsRouteWithChildren
  '/api/base/sections': typeof ApiBaseSectionsRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/atividades/preencher/$token': typeof AtividadesPreencherTokenRoute
  '/avaliacao-desempenho/preencher/$token': typeof AvaliacaoDesempenhoPreencherTokenRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/gerenciamento/usuarios/novo': typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  '/projetos/$projectId/andamento': typeof AuthenticatedProjetosProjectIdAndamentoRoute
  '/projetos/$projectId/areas': typeof AuthenticatedProjetosProjectIdAreasRoute
  '/projetos/$projectId/atividades': typeof AuthenticatedProjetosProjectIdAtividadesRoute
  '/projetos/$projectId/avaliacao-desempenho': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  '/projetos/$projectId/base': typeof AuthenticatedProjetosProjectIdBaseRoute
  '/projetos/$projectId/colaboradores': typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  '/projetos/$projectId/configuracoes': typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  '/projetos/$projectId/historico': typeof AuthenticatedProjetosProjectIdHistoricoRoute
  '/projetos/$projectId/organograma': typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  '/projetos/$projectId/pam': typeof AuthenticatedProjetosProjectIdPamRoute
  '/api/base/fields/$fieldId': typeof ApiBaseFieldsFieldIdRoute
  '/api/base/fields/order': typeof ApiBaseFieldsOrderRoute
  '/api/base/options/$optionId': typeof ApiBaseOptionsOptionIdRoute
  '/api/projects/$projectId/areas': typeof ApiProjectsProjectIdAreasRouteWithChildren
  '/api/public/activity-draft/$token': typeof ApiPublicActivityDraftTokenRoute
  '/api/public/activity-form/$token': typeof ApiPublicActivityFormTokenRoute
  '/api/public/activity-response/$token': typeof ApiPublicActivityResponseTokenRoute
  '/api/public/pam-complete/$token': typeof ApiPublicPamCompleteTokenRoute
  '/api/public/pam-draft/$token': typeof ApiPublicPamDraftTokenRoute
  '/api/public/pam/$token': typeof ApiPublicPamTokenRoute
  '/api/public/performance-draft/$token': typeof ApiPublicPerformanceDraftTokenRoute
  '/api/public/performance-form/$token': typeof ApiPublicPerformanceFormTokenRoute
  '/api/public/performance-response/$token': typeof ApiPublicPerformanceResponseTokenRoute
  '/gerenciamento/usuarios': typeof AuthenticatedGerenciamentoUsuariosIndexRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdIndexRoute
  '/projetos/$projectId/descricao-cargo/$dcId': typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  '/projetos/$projectId/descricao-cargo/novo': typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  '/api/projects/$projectId/areas/$areaId': typeof ApiProjectsProjectIdAreasAreaIdRoute
  '/projetos/$projectId/descricao-cargo': typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
  '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/api/base': typeof ApiBaseRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/users': typeof ApiUsersRoute
  '/pam/$token': typeof PamTokenRoute
  '/_authenticated/gerenciamento/atrelar': typeof AuthenticatedGerenciamentoAtrelarRoute
  '/_authenticated/gerenciamento/bases': typeof AuthenticatedGerenciamentoBasesRoute
  '/_authenticated/gerenciamento/usuarios': typeof AuthenticatedGerenciamentoUsuariosRouteWithChildren
  '/_authenticated/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRouteWithChildren
  '/_authenticated/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/api/base/access': typeof ApiBaseAccessRoute
  '/api/base/fields': typeof ApiBaseFieldsRouteWithChildren
  '/api/base/options': typeof ApiBaseOptionsRouteWithChildren
  '/api/base/sections': typeof ApiBaseSectionsRoute
  '/api/projects/$projectId': typeof ApiProjectsProjectIdRouteWithChildren
  '/atividades/preencher/$token': typeof AtividadesPreencherTokenRoute
  '/avaliacao-desempenho/preencher/$token': typeof AvaliacaoDesempenhoPreencherTokenRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/_authenticated/gerenciamento/usuarios/novo': typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  '/_authenticated/projetos/$projectId/andamento': typeof AuthenticatedProjetosProjectIdAndamentoRoute
  '/_authenticated/projetos/$projectId/areas': typeof AuthenticatedProjetosProjectIdAreasRoute
  '/_authenticated/projetos/$projectId/atividades': typeof AuthenticatedProjetosProjectIdAtividadesRoute
  '/_authenticated/projetos/$projectId/avaliacao-desempenho': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  '/_authenticated/projetos/$projectId/base': typeof AuthenticatedProjetosProjectIdBaseRoute
  '/_authenticated/projetos/$projectId/colaboradores': typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  '/_authenticated/projetos/$projectId/configuracoes': typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  '/_authenticated/projetos/$projectId/descricao-cargo': typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren
  '/_authenticated/projetos/$projectId/historico': typeof AuthenticatedProjetosProjectIdHistoricoRoute
  '/_authenticated/projetos/$projectId/organograma': typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  '/_authenticated/projetos/$projectId/pam': typeof AuthenticatedProjetosProjectIdPamRoute
  '/api/base/fields/$fieldId': typeof ApiBaseFieldsFieldIdRoute
  '/api/base/fields/order': typeof ApiBaseFieldsOrderRoute
  '/api/base/options/$optionId': typeof ApiBaseOptionsOptionIdRoute
  '/api/projects/$projectId/areas': typeof ApiProjectsProjectIdAreasRouteWithChildren
  '/api/public/activity-draft/$token': typeof ApiPublicActivityDraftTokenRoute
  '/api/public/activity-form/$token': typeof ApiPublicActivityFormTokenRoute
  '/api/public/activity-response/$token': typeof ApiPublicActivityResponseTokenRoute
  '/api/public/pam-complete/$token': typeof ApiPublicPamCompleteTokenRoute
  '/api/public/pam-draft/$token': typeof ApiPublicPamDraftTokenRoute
  '/api/public/pam/$token': typeof ApiPublicPamTokenRoute
  '/api/public/performance-draft/$token': typeof ApiPublicPerformanceDraftTokenRoute
  '/api/public/performance-form/$token': typeof ApiPublicPerformanceFormTokenRoute
  '/api/public/performance-response/$token': typeof ApiPublicPerformanceResponseTokenRoute
  '/_authenticated/gerenciamento/usuarios/': typeof AuthenticatedGerenciamentoUsuariosIndexRoute
  '/_authenticated/projetos/$projectId/': typeof AuthenticatedProjetosProjectIdIndexRoute
  '/_authenticated/projetos/$projectId/descricao-cargo/$dcId': typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  '/_authenticated/projetos/$projectId/descricao-cargo/novo': typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  '/api/projects/$projectId/areas/$areaId': typeof ApiProjectsProjectIdAreasAreaIdRoute
  '/_authenticated/projetos/$projectId/descricao-cargo/': typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
  '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/projetos'
    | '/api/base'
    | '/api/me'
    | '/api/projects'
    | '/api/users'
    | '/pam/$token'
    | '/gerenciamento/atrelar'
    | '/gerenciamento/bases'
    | '/gerenciamento/usuarios'
    | '/projetos/$projectId'
    | '/projetos/novo'
    | '/api/base/access'
    | '/api/base/fields'
    | '/api/base/options'
    | '/api/base/sections'
    | '/api/projects/$projectId'
    | '/atividades/preencher/$token'
    | '/avaliacao-desempenho/preencher/$token'
    | '/projetos/'
    | '/gerenciamento/usuarios/novo'
    | '/projetos/$projectId/andamento'
    | '/projetos/$projectId/areas'
    | '/projetos/$projectId/atividades'
    | '/projetos/$projectId/avaliacao-desempenho'
    | '/projetos/$projectId/base'
    | '/projetos/$projectId/colaboradores'
    | '/projetos/$projectId/configuracoes'
    | '/projetos/$projectId/descricao-cargo'
    | '/projetos/$projectId/historico'
    | '/projetos/$projectId/organograma'
    | '/projetos/$projectId/pam'
    | '/api/base/fields/$fieldId'
    | '/api/base/fields/order'
    | '/api/base/options/$optionId'
    | '/api/projects/$projectId/areas'
    | '/api/public/activity-draft/$token'
    | '/api/public/activity-form/$token'
    | '/api/public/activity-response/$token'
    | '/api/public/pam-complete/$token'
    | '/api/public/pam-draft/$token'
    | '/api/public/pam/$token'
    | '/api/public/performance-draft/$token'
    | '/api/public/performance-form/$token'
    | '/api/public/performance-response/$token'
    | '/gerenciamento/usuarios/'
    | '/projetos/$projectId/'
    | '/projetos/$projectId/descricao-cargo/$dcId'
    | '/projetos/$projectId/descricao-cargo/novo'
    | '/api/projects/$projectId/areas/$areaId'
    | '/projetos/$projectId/descricao-cargo/'
    | '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/api/base'
    | '/api/me'
    | '/api/projects'
    | '/api/users'
    | '/pam/$token'
    | '/gerenciamento/atrelar'
    | '/gerenciamento/bases'
    | '/projetos/novo'
    | '/api/base/access'
    | '/api/base/fields'
    | '/api/base/options'
    | '/api/base/sections'
    | '/api/projects/$projectId'
    | '/atividades/preencher/$token'
    | '/avaliacao-desempenho/preencher/$token'
    | '/projetos'
    | '/gerenciamento/usuarios/novo'
    | '/projetos/$projectId/andamento'
    | '/projetos/$projectId/areas'
    | '/projetos/$projectId/atividades'
    | '/projetos/$projectId/avaliacao-desempenho'
    | '/projetos/$projectId/base'
    | '/projetos/$projectId/colaboradores'
    | '/projetos/$projectId/configuracoes'
    | '/projetos/$projectId/historico'
    | '/projetos/$projectId/organograma'
    | '/projetos/$projectId/pam'
    | '/api/base/fields/$fieldId'
    | '/api/base/fields/order'
    | '/api/base/options/$optionId'
    | '/api/projects/$projectId/areas'
    | '/api/public/activity-draft/$token'
    | '/api/public/activity-form/$token'
    | '/api/public/activity-response/$token'
    | '/api/public/pam-complete/$token'
    | '/api/public/pam-draft/$token'
    | '/api/public/pam/$token'
    | '/api/public/performance-draft/$token'
    | '/api/public/performance-form/$token'
    | '/api/public/performance-response/$token'
    | '/gerenciamento/usuarios'
    | '/projetos/$projectId'
    | '/projetos/$projectId/descricao-cargo/$dcId'
    | '/projetos/$projectId/descricao-cargo/novo'
    | '/api/projects/$projectId/areas/$areaId'
    | '/projetos/$projectId/descricao-cargo'
    | '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/health'
    | '/login'
    | '/_authenticated/projetos'
    | '/api/base'
    | '/api/me'
    | '/api/projects'
    | '/api/users'
    | '/pam/$token'
    | '/_authenticated/gerenciamento/atrelar'
    | '/_authenticated/gerenciamento/bases'
    | '/_authenticated/gerenciamento/usuarios'
    | '/_authenticated/projetos/$projectId'
    | '/_authenticated/projetos/novo'
    | '/api/base/access'
    | '/api/base/fields'
    | '/api/base/options'
    | '/api/base/sections'
    | '/api/projects/$projectId'
    | '/atividades/preencher/$token'
    | '/avaliacao-desempenho/preencher/$token'
    | '/_authenticated/projetos/'
    | '/_authenticated/gerenciamento/usuarios/novo'
    | '/_authenticated/projetos/$projectId/andamento'
    | '/_authenticated/projetos/$projectId/areas'
    | '/_authenticated/projetos/$projectId/atividades'
    | '/_authenticated/projetos/$projectId/avaliacao-desempenho'
    | '/_authenticated/projetos/$projectId/base'
    | '/_authenticated/projetos/$projectId/colaboradores'
    | '/_authenticated/projetos/$projectId/configuracoes'
    | '/_authenticated/projetos/$projectId/descricao-cargo'
    | '/_authenticated/projetos/$projectId/historico'
    | '/_authenticated/projetos/$projectId/organograma'
    | '/_authenticated/projetos/$projectId/pam'
    | '/api/base/fields/$fieldId'
    | '/api/base/fields/order'
    | '/api/base/options/$optionId'
    | '/api/projects/$projectId/areas'
    | '/api/public/activity-draft/$token'
    | '/api/public/activity-form/$token'
    | '/api/public/activity-response/$token'
    | '/api/public/pam-complete/$token'
    | '/api/public/pam-draft/$token'
    | '/api/public/pam/$token'
    | '/api/public/performance-draft/$token'
    | '/api/public/performance-form/$token'
    | '/api/public/performance-response/$token'
    | '/_authenticated/gerenciamento/usuarios/'
    | '/_authenticated/projetos/$projectId/'
    | '/_authenticated/projetos/$projectId/descricao-cargo/$dcId'
    | '/_authenticated/projetos/$projectId/descricao-cargo/novo'
    | '/api/projects/$projectId/areas/$areaId'
    | '/_authenticated/projetos/$projectId/descricao-cargo/'
    | '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ApiBaseRoute: typeof ApiBaseRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRoute
  PamTokenRoute: typeof PamTokenRoute
  AtividadesPreencherTokenRoute: typeof AtividadesPreencherTokenRoute
  AvaliacaoDesempenhoPreencherTokenRoute: typeof AvaliacaoDesempenhoPreencherTokenRoute
  ApiPublicActivityDraftTokenRoute: typeof ApiPublicActivityDraftTokenRoute
  ApiPublicActivityFormTokenRoute: typeof ApiPublicActivityFormTokenRoute
  ApiPublicActivityResponseTokenRoute: typeof ApiPublicActivityResponseTokenRoute
  ApiPublicPamCompleteTokenRoute: typeof ApiPublicPamCompleteTokenRoute
  ApiPublicPamDraftTokenRoute: typeof ApiPublicPamDraftTokenRoute
  ApiPublicPamTokenRoute: typeof ApiPublicPamTokenRoute
  ApiPublicPerformanceDraftTokenRoute: typeof ApiPublicPerformanceDraftTokenRoute
  ApiPublicPerformanceFormTokenRoute: typeof ApiPublicPerformanceFormTokenRoute
  ApiPublicPerformanceResponseTokenRoute: typeof ApiPublicPerformanceResponseTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pam/$token': {
      id: '/pam/$token'
      path: '/pam/$token'
      fullPath: '/pam/$token'
      preLoaderRoute: typeof PamTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/base': {
      id: '/api/base'
      path: '/api/base'
      fullPath: '/api/base'
      preLoaderRoute: typeof ApiBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/avaliacao-desempenho/preencher/$token': {
      id: '/avaliacao-desempenho/preencher/$token'
      path: '/avaliacao-desempenho/preencher/$token'
      fullPath: '/avaliacao-desempenho/preencher/$token'
      preLoaderRoute: typeof AvaliacaoDesempenhoPreencherTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/preencher/$token': {
      id: '/atividades/preencher/$token'
      path: '/atividades/preencher/$token'
      fullPath: '/atividades/preencher/$token'
      preLoaderRoute: typeof AtividadesPreencherTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId': {
      id: '/api/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/projects/$projectId'
      preLoaderRoute: typeof ApiProjectsProjectIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
    '/api/base/sections': {
      id: '/api/base/sections'
      path: '/sections'
      fullPath: '/api/base/sections'
      preLoaderRoute: typeof ApiBaseSectionsRouteImport
      parentRoute: typeof ApiBaseRoute
    }
    '/api/base/options': {
      id: '/api/base/options'
      path: '/options'
      fullPath: '/api/base/options'
      preLoaderRoute: typeof ApiBaseOptionsRouteImport
      parentRoute: typeof ApiBaseRoute
    }
    '/api/base/fields': {
      id: '/api/base/fields'
      path: '/fields'
      fullPath: '/api/base/fields'
      preLoaderRoute: typeof ApiBaseFieldsRouteImport
      parentRoute: typeof ApiBaseRoute
    }
    '/api/base/access': {
      id: '/api/base/access'
      path: '/access'
      fullPath: '/api/base/access'
      preLoaderRoute: typeof ApiBaseAccessRouteImport
      parentRoute: typeof ApiBaseRoute
    }
    '/_authenticated/projetos/novo': {
      id: '/_authenticated/projetos/novo'
      path: '/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof AuthenticatedProjetosNovoRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/projetos/$projectId': {
      id: '/_authenticated/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/gerenciamento/usuarios': {
      id: '/_authenticated/gerenciamento/usuarios'
      path: '/gerenciamento/usuarios'
      fullPath: '/gerenciamento/usuarios'
      preLoaderRoute: typeof AuthenticatedGerenciamentoUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gerenciamento/bases': {
      id: '/_authenticated/gerenciamento/bases'
      path: '/gerenciamento/bases'
      fullPath: '/gerenciamento/bases'
      preLoaderRoute: typeof AuthenticatedGerenciamentoBasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gerenciamento/atrelar': {
      id: '/_authenticated/gerenciamento/atrelar'
      path: '/gerenciamento/atrelar'
      fullPath: '/gerenciamento/atrelar'
      preLoaderRoute: typeof AuthenticatedGerenciamentoAtrelarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos/$projectId/': {
      id: '/_authenticated/projetos/$projectId/'
      path: '/'
      fullPath: '/projetos/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/gerenciamento/usuarios/': {
      id: '/_authenticated/gerenciamento/usuarios/'
      path: '/'
      fullPath: '/gerenciamento/usuarios/'
      preLoaderRoute: typeof AuthenticatedGerenciamentoUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedGerenciamentoUsuariosRoute
    }
    '/api/public/performance-response/$token': {
      id: '/api/public/performance-response/$token'
      path: '/api/public/performance-response/$token'
      fullPath: '/api/public/performance-response/$token'
      preLoaderRoute: typeof ApiPublicPerformanceResponseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/performance-form/$token': {
      id: '/api/public/performance-form/$token'
      path: '/api/public/performance-form/$token'
      fullPath: '/api/public/performance-form/$token'
      preLoaderRoute: typeof ApiPublicPerformanceFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/performance-draft/$token': {
      id: '/api/public/performance-draft/$token'
      path: '/api/public/performance-draft/$token'
      fullPath: '/api/public/performance-draft/$token'
      preLoaderRoute: typeof ApiPublicPerformanceDraftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pam/$token': {
      id: '/api/public/pam/$token'
      path: '/api/public/pam/$token'
      fullPath: '/api/public/pam/$token'
      preLoaderRoute: typeof ApiPublicPamTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pam-draft/$token': {
      id: '/api/public/pam-draft/$token'
      path: '/api/public/pam-draft/$token'
      fullPath: '/api/public/pam-draft/$token'
      preLoaderRoute: typeof ApiPublicPamDraftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pam-complete/$token': {
      id: '/api/public/pam-complete/$token'
      path: '/api/public/pam-complete/$token'
      fullPath: '/api/public/pam-complete/$token'
      preLoaderRoute: typeof ApiPublicPamCompleteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activity-response/$token': {
      id: '/api/public/activity-response/$token'
      path: '/api/public/activity-response/$token'
      fullPath: '/api/public/activity-response/$token'
      preLoaderRoute: typeof ApiPublicActivityResponseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activity-form/$token': {
      id: '/api/public/activity-form/$token'
      path: '/api/public/activity-form/$token'
      fullPath: '/api/public/activity-form/$token'
      preLoaderRoute: typeof ApiPublicActivityFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activity-draft/$token': {
      id: '/api/public/activity-draft/$token'
      path: '/api/public/activity-draft/$token'
      fullPath: '/api/public/activity-draft/$token'
      preLoaderRoute: typeof ApiPublicActivityDraftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/areas': {
      id: '/api/projects/$projectId/areas'
      path: '/areas'
      fullPath: '/api/projects/$projectId/areas'
      preLoaderRoute: typeof ApiProjectsProjectIdAreasRouteImport
      parentRoute: typeof ApiProjectsProjectIdRoute
    }
    '/api/base/options/$optionId': {
      id: '/api/base/options/$optionId'
      path: '/$optionId'
      fullPath: '/api/base/options/$optionId'
      preLoaderRoute: typeof ApiBaseOptionsOptionIdRouteImport
      parentRoute: typeof ApiBaseOptionsRoute
    }
    '/api/base/fields/order': {
      id: '/api/base/fields/order'
      path: '/order'
      fullPath: '/api/base/fields/order'
      preLoaderRoute: typeof ApiBaseFieldsOrderRouteImport
      parentRoute: typeof ApiBaseFieldsRoute
    }
    '/api/base/fields/$fieldId': {
      id: '/api/base/fields/$fieldId'
      path: '/$fieldId'
      fullPath: '/api/base/fields/$fieldId'
      preLoaderRoute: typeof ApiBaseFieldsFieldIdRouteImport
      parentRoute: typeof ApiBaseFieldsRoute
    }
    '/_authenticated/projetos/$projectId/pam': {
      id: '/_authenticated/projetos/$projectId/pam'
      path: '/pam'
      fullPath: '/projetos/$projectId/pam'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdPamRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/organograma': {
      id: '/_authenticated/projetos/$projectId/organograma'
      path: '/organograma'
      fullPath: '/projetos/$projectId/organograma'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdOrganogramaRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/historico': {
      id: '/_authenticated/projetos/$projectId/historico'
      path: '/historico'
      fullPath: '/projetos/$projectId/historico'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdHistoricoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo'
      path: '/descricao-cargo'
      fullPath: '/projetos/$projectId/descricao-cargo'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/configuracoes': {
      id: '/_authenticated/projetos/$projectId/configuracoes'
      path: '/configuracoes'
      fullPath: '/projetos/$projectId/configuracoes'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/colaboradores': {
      id: '/_authenticated/projetos/$projectId/colaboradores'
      path: '/colaboradores'
      fullPath: '/projetos/$projectId/colaboradores'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdColaboradoresRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/base': {
      id: '/_authenticated/projetos/$projectId/base'
      path: '/base'
      fullPath: '/projetos/$projectId/base'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdBaseRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/avaliacao-desempenho': {
      id: '/_authenticated/projetos/$projectId/avaliacao-desempenho'
      path: '/avaliacao-desempenho'
      fullPath: '/projetos/$projectId/avaliacao-desempenho'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/atividades': {
      id: '/_authenticated/projetos/$projectId/atividades'
      path: '/atividades'
      fullPath: '/projetos/$projectId/atividades'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAtividadesRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/areas': {
      id: '/_authenticated/projetos/$projectId/areas'
      path: '/areas'
      fullPath: '/projetos/$projectId/areas'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAreasRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/andamento': {
      id: '/_authenticated/projetos/$projectId/andamento'
      path: '/andamento'
      fullPath: '/projetos/$projectId/andamento'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAndamentoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/gerenciamento/usuarios/novo': {
      id: '/_authenticated/gerenciamento/usuarios/novo'
      path: '/novo'
      fullPath: '/gerenciamento/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedGerenciamentoUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedGerenciamentoUsuariosRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo/': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo/'
      path: '/'
      fullPath: '/projetos/$projectId/descricao-cargo/'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRoute
    }
    '/api/projects/$projectId/areas/$areaId': {
      id: '/api/projects/$projectId/areas/$areaId'
      path: '/$areaId'
      fullPath: '/api/projects/$projectId/areas/$areaId'
      preLoaderRoute: typeof ApiProjectsProjectIdAreasAreaIdRouteImport
      parentRoute: typeof ApiProjectsProjectIdAreasRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo/novo': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo/novo'
      path: '/novo'
      fullPath: '/projetos/$projectId/descricao-cargo/novo'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo/$dcId': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo/$dcId'
      path: '/$dcId'
      fullPath: '/projetos/$projectId/descricao-cargo/$dcId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRoute
    }
    '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': {
      id: '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
      path: '/comparar/$reviewId'
      fullPath: '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute
    }
  }
}

interface AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren {
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}

const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren: AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren =
  {
    AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute:
      AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute,
  }

const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren =
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute._addFileChildren(
    AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren,
  )

interface AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren {
  AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
}

const AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren: AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren =
  {
    AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute,
    AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute,
    AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute,
  }

const AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren =
  AuthenticatedProjetosProjectIdDescricaoCargoRoute._addFileChildren(
    AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren,
  )

interface AuthenticatedProjetosProjectIdRouteChildren {
  AuthenticatedProjetosProjectIdAndamentoRoute: typeof AuthenticatedProjetosProjectIdAndamentoRoute
  AuthenticatedProjetosProjectIdAreasRoute: typeof AuthenticatedProjetosProjectIdAreasRoute
  AuthenticatedProjetosProjectIdAtividadesRoute: typeof AuthenticatedProjetosProjectIdAtividadesRoute
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  AuthenticatedProjetosProjectIdBaseRoute: typeof AuthenticatedProjetosProjectIdBaseRoute
  AuthenticatedProjetosProjectIdColaboradoresRoute: typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  AuthenticatedProjetosProjectIdConfiguracoesRoute: typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  AuthenticatedProjetosProjectIdDescricaoCargoRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren
  AuthenticatedProjetosProjectIdHistoricoRoute: typeof AuthenticatedProjetosProjectIdHistoricoRoute
  AuthenticatedProjetosProjectIdOrganogramaRoute: typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  AuthenticatedProjetosProjectIdPamRoute: typeof AuthenticatedProjetosProjectIdPamRoute
  AuthenticatedProjetosProjectIdIndexRoute: typeof AuthenticatedProjetosProjectIdIndexRoute
}

const AuthenticatedProjetosProjectIdRouteChildren: AuthenticatedProjetosProjectIdRouteChildren =
  {
    AuthenticatedProjetosProjectIdAndamentoRoute:
      AuthenticatedProjetosProjectIdAndamentoRoute,
    AuthenticatedProjetosProjectIdAreasRoute:
      AuthenticatedProjetosProjectIdAreasRoute,
    AuthenticatedProjetosProjectIdAtividadesRoute:
      AuthenticatedProjetosProjectIdAtividadesRoute,
    AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute:
      AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren,
    AuthenticatedProjetosProjectIdBaseRoute:
      AuthenticatedProjetosProjectIdBaseRoute,
    AuthenticatedProjetosProjectIdColaboradoresRoute:
      AuthenticatedProjetosProjectIdColaboradoresRoute,
    AuthenticatedProjetosProjectIdConfiguracoesRoute:
      AuthenticatedProjetosProjectIdConfiguracoesRoute,
    AuthenticatedProjetosProjectIdDescricaoCargoRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren,
    AuthenticatedProjetosProjectIdHistoricoRoute:
      AuthenticatedProjetosProjectIdHistoricoRoute,
    AuthenticatedProjetosProjectIdOrganogramaRoute:
      AuthenticatedProjetosProjectIdOrganogramaRoute,
    AuthenticatedProjetosProjectIdPamRoute:
      AuthenticatedProjetosProjectIdPamRoute,
    AuthenticatedProjetosProjectIdIndexRoute:
      AuthenticatedProjetosProjectIdIndexRoute,
  }

const AuthenticatedProjetosProjectIdRouteWithChildren =
  AuthenticatedProjetosProjectIdRoute._addFileChildren(
    AuthenticatedProjetosProjectIdRouteChildren,
  )

interface AuthenticatedProjetosRouteChildren {
  AuthenticatedProjetosProjectIdRoute: typeof AuthenticatedProjetosProjectIdRouteWithChildren
  AuthenticatedProjetosNovoRoute: typeof AuthenticatedProjetosNovoRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
}

const AuthenticatedProjetosRouteChildren: AuthenticatedProjetosRouteChildren = {
  AuthenticatedProjetosProjectIdRoute:
    AuthenticatedProjetosProjectIdRouteWithChildren,
  AuthenticatedProjetosNovoRoute: AuthenticatedProjetosNovoRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
}

const AuthenticatedProjetosRouteWithChildren =
  AuthenticatedProjetosRoute._addFileChildren(
    AuthenticatedProjetosRouteChildren,
  )

interface AuthenticatedGerenciamentoUsuariosRouteChildren {
  AuthenticatedGerenciamentoUsuariosNovoRoute: typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  AuthenticatedGerenciamentoUsuariosIndexRoute: typeof AuthenticatedGerenciamentoUsuariosIndexRoute
}

const AuthenticatedGerenciamentoUsuariosRouteChildren: AuthenticatedGerenciamentoUsuariosRouteChildren =
  {
    AuthenticatedGerenciamentoUsuariosNovoRoute:
      AuthenticatedGerenciamentoUsuariosNovoRoute,
    AuthenticatedGerenciamentoUsuariosIndexRoute:
      AuthenticatedGerenciamentoUsuariosIndexRoute,
  }

const AuthenticatedGerenciamentoUsuariosRouteWithChildren =
  AuthenticatedGerenciamentoUsuariosRoute._addFileChildren(
    AuthenticatedGerenciamentoUsuariosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRouteWithChildren
  AuthenticatedGerenciamentoAtrelarRoute: typeof AuthenticatedGerenciamentoAtrelarRoute
  AuthenticatedGerenciamentoBasesRoute: typeof AuthenticatedGerenciamentoBasesRoute
  AuthenticatedGerenciamentoUsuariosRoute: typeof AuthenticatedGerenciamentoUsuariosRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjetosRoute: AuthenticatedProjetosRouteWithChildren,
  AuthenticatedGerenciamentoAtrelarRoute:
    AuthenticatedGerenciamentoAtrelarRoute,
  AuthenticatedGerenciamentoBasesRoute: AuthenticatedGerenciamentoBasesRoute,
  AuthenticatedGerenciamentoUsuariosRoute:
    AuthenticatedGerenciamentoUsuariosRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiBaseFieldsRouteChildren {
  ApiBaseFieldsFieldIdRoute: typeof ApiBaseFieldsFieldIdRoute
  ApiBaseFieldsOrderRoute: typeof ApiBaseFieldsOrderRoute
}

const ApiBaseFieldsRouteChildren: ApiBaseFieldsRouteChildren = {
  ApiBaseFieldsFieldIdRoute: ApiBaseFieldsFieldIdRoute,
  ApiBaseFieldsOrderRoute: ApiBaseFieldsOrderRoute,
}

const ApiBaseFieldsRouteWithChildren = ApiBaseFieldsRoute._addFileChildren(
  ApiBaseFieldsRouteChildren,
)

interface ApiBaseOptionsRouteChildren {
  ApiBaseOptionsOptionIdRoute: typeof ApiBaseOptionsOptionIdRoute
}

const ApiBaseOptionsRouteChildren: ApiBaseOptionsRouteChildren = {
  ApiBaseOptionsOptionIdRoute: ApiBaseOptionsOptionIdRoute,
}

const ApiBaseOptionsRouteWithChildren = ApiBaseOptionsRoute._addFileChildren(
  ApiBaseOptionsRouteChildren,
)

interface ApiBaseRouteChildren {
  ApiBaseAccessRoute: typeof ApiBaseAccessRoute
  ApiBaseFieldsRoute: typeof ApiBaseFieldsRouteWithChildren
  ApiBaseOptionsRoute: typeof ApiBaseOptionsRouteWithChildren
  ApiBaseSectionsRoute: typeof ApiBaseSectionsRoute
}

const ApiBaseRouteChildren: ApiBaseRouteChildren = {
  ApiBaseAccessRoute: ApiBaseAccessRoute,
  ApiBaseFieldsRoute: ApiBaseFieldsRouteWithChildren,
  ApiBaseOptionsRoute: ApiBaseOptionsRouteWithChildren,
  ApiBaseSectionsRoute: ApiBaseSectionsRoute,
}

const ApiBaseRouteWithChildren =
  ApiBaseRoute._addFileChildren(ApiBaseRouteChildren)

interface ApiProjectsProjectIdAreasRouteChildren {
  ApiProjectsProjectIdAreasAreaIdRoute: typeof ApiProjectsProjectIdAreasAreaIdRoute
}

const ApiProjectsProjectIdAreasRouteChildren: ApiProjectsProjectIdAreasRouteChildren =
  {
    ApiProjectsProjectIdAreasAreaIdRoute: ApiProjectsProjectIdAreasAreaIdRoute,
  }

const ApiProjectsProjectIdAreasRouteWithChildren =
  ApiProjectsProjectIdAreasRoute._addFileChildren(
    ApiProjectsProjectIdAreasRouteChildren,
  )

interface ApiProjectsProjectIdRouteChildren {
  ApiProjectsProjectIdAreasRoute: typeof ApiProjectsProjectIdAreasRouteWithChildren
}

const ApiProjectsProjectIdRouteChildren: ApiProjectsProjectIdRouteChildren = {
  ApiProjectsProjectIdAreasRoute: ApiProjectsProjectIdAreasRouteWithChildren,
}

const ApiProjectsProjectIdRouteWithChildren =
  ApiProjectsProjectIdRoute._addFileChildren(ApiProjectsProjectIdRouteChildren)

interface ApiProjectsRouteChildren {
  ApiProjectsProjectIdRoute: typeof ApiProjectsProjectIdRouteWithChildren
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsProjectIdRoute: ApiProjectsProjectIdRouteWithChildren,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ApiBaseRoute: ApiBaseRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
  ApiUsersRoute: ApiUsersRoute,
  PamTokenRoute: PamTokenRoute,
  AtividadesPreencherTokenRoute: AtividadesPreencherTokenRoute,
  AvaliacaoDesempenhoPreencherTokenRoute:
    AvaliacaoDesempenhoPreencherTokenRoute,
  ApiPublicActivityDraftTokenRoute: ApiPublicActivityDraftTokenRoute,
  ApiPublicActivityFormTokenRoute: ApiPublicActivityFormTokenRoute,
  ApiPublicActivityResponseTokenRoute: ApiPublicActivityResponseTokenRoute,
  ApiPublicPamCompleteTokenRoute: ApiPublicPamCompleteTokenRoute,
  ApiPublicPamDraftTokenRoute: ApiPublicPamDraftTokenRoute,
  ApiPublicPamTokenRoute: ApiPublicPamTokenRoute,
  ApiPublicPerformanceDraftTokenRoute: ApiPublicPerformanceDraftTokenRoute,
  ApiPublicPerformanceFormTokenRoute: ApiPublicPerformanceFormTokenRoute,
  ApiPublicPerformanceResponseTokenRoute:
    ApiPublicPerformanceResponseTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
