/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos.index'
import { Route as AvaliacaoDesempenhoPreencherTokenRouteImport } from './routes/avaliacao-desempenho.preencher.$token'
import { Route as AtividadesPreencherTokenRouteImport } from './routes/atividades.preencher.$token'
import { Route as AuthenticatedProjetosNovoRouteImport } from './routes/_authenticated/projetos.novo'
import { Route as AuthenticatedProjetosProjectIdRouteImport } from './routes/_authenticated/projetos.$projectId'
import { Route as AuthenticatedGerenciamentoUsuariosRouteImport } from './routes/_authenticated/gerenciamento.usuarios'
import { Route as AuthenticatedGerenciamentoBasesRouteImport } from './routes/_authenticated/gerenciamento.bases'
import { Route as AuthenticatedGerenciamentoAtrelarRouteImport } from './routes/_authenticated/gerenciamento.atrelar'
import { Route as AuthenticatedProjetosProjectIdIndexRouteImport } from './routes/_authenticated/projetos.$projectId.index'
import { Route as AuthenticatedGerenciamentoUsuariosIndexRouteImport } from './routes/_authenticated/gerenciamento.usuarios.index'
import { Route as ApiPublicPerformanceResponseTokenRouteImport } from './routes/api/public/performance-response.$token'
import { Route as ApiPublicPerformanceFormTokenRouteImport } from './routes/api/public/performance-form.$token'
import { Route as ApiPublicPerformanceDraftTokenRouteImport } from './routes/api/public/performance-draft.$token'
import { Route as ApiPublicActivityResponseTokenRouteImport } from './routes/api/public/activity-response.$token'
import { Route as ApiPublicActivityFormTokenRouteImport } from './routes/api/public/activity-form.$token'
import { Route as ApiPublicActivityDraftTokenRouteImport } from './routes/api/public/activity-draft.$token'
import { Route as AuthenticatedProjetosProjectIdOrganogramaRouteImport } from './routes/_authenticated/projetos.$projectId.organograma'
import { Route as AuthenticatedProjetosProjectIdHistoricoRouteImport } from './routes/_authenticated/projetos.$projectId.historico'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo'
import { Route as AuthenticatedProjetosProjectIdConfiguracoesRouteImport } from './routes/_authenticated/projetos.$projectId.configuracoes'
import { Route as AuthenticatedProjetosProjectIdColaboradoresRouteImport } from './routes/_authenticated/projetos.$projectId.colaboradores'
import { Route as AuthenticatedProjetosProjectIdBaseRouteImport } from './routes/_authenticated/projetos.$projectId.base'
import { Route as AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteImport } from './routes/_authenticated/projetos.$projectId.avaliacao-desempenho'
import { Route as AuthenticatedProjetosProjectIdAtividadesRouteImport } from './routes/_authenticated/projetos.$projectId.atividades'
import { Route as AuthenticatedProjetosProjectIdAreasRouteImport } from './routes/_authenticated/projetos.$projectId.areas'
import { Route as AuthenticatedProjetosProjectIdAndamentoRouteImport } from './routes/_authenticated/projetos.$projectId.andamento'
import { Route as AuthenticatedGerenciamentoUsuariosNovoRouteImport } from './routes/_authenticated/gerenciamento.usuarios.novo'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoIndexRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo.index'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoNovoRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo.novo'
import { Route as AuthenticatedProjetosProjectIdDescricaoCargoDcIdRouteImport } from './routes/_authenticated/projetos.$projectId.descricao-cargo.$dcId'
import { Route as AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRouteImport } from './routes/_authenticated/projetos.$projectId.avaliacao-desempenho.comparar.$reviewId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AvaliacaoDesempenhoPreencherTokenRoute =
  AvaliacaoDesempenhoPreencherTokenRouteImport.update({
    id: '/avaliacao-desempenho/preencher/$token',
    path: '/avaliacao-desempenho/preencher/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtividadesPreencherTokenRoute =
  AtividadesPreencherTokenRouteImport.update({
    id: '/atividades/preencher/$token',
    path: '/atividades/preencher/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjetosNovoRoute =
  AuthenticatedProjetosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AuthenticatedProjetosProjectIdRoute =
  AuthenticatedProjetosProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjetosRoute,
  } as any)
const AuthenticatedGerenciamentoUsuariosRoute =
  AuthenticatedGerenciamentoUsuariosRouteImport.update({
    id: '/gerenciamento/usuarios',
    path: '/gerenciamento/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGerenciamentoBasesRoute =
  AuthenticatedGerenciamentoBasesRouteImport.update({
    id: '/gerenciamento/bases',
    path: '/gerenciamento/bases',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGerenciamentoAtrelarRoute =
  AuthenticatedGerenciamentoAtrelarRouteImport.update({
    id: '/gerenciamento/atrelar',
    path: '/gerenciamento/atrelar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetosProjectIdIndexRoute =
  AuthenticatedProjetosProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedGerenciamentoUsuariosIndexRoute =
  AuthenticatedGerenciamentoUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGerenciamentoUsuariosRoute,
  } as any)
const ApiPublicPerformanceResponseTokenRoute =
  ApiPublicPerformanceResponseTokenRouteImport.update({
    id: '/api/public/performance-response/$token',
    path: '/api/public/performance-response/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPerformanceFormTokenRoute =
  ApiPublicPerformanceFormTokenRouteImport.update({
    id: '/api/public/performance-form/$token',
    path: '/api/public/performance-form/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPerformanceDraftTokenRoute =
  ApiPublicPerformanceDraftTokenRouteImport.update({
    id: '/api/public/performance-draft/$token',
    path: '/api/public/performance-draft/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivityResponseTokenRoute =
  ApiPublicActivityResponseTokenRouteImport.update({
    id: '/api/public/activity-response/$token',
    path: '/api/public/activity-response/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivityFormTokenRoute =
  ApiPublicActivityFormTokenRouteImport.update({
    id: '/api/public/activity-form/$token',
    path: '/api/public/activity-form/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivityDraftTokenRoute =
  ApiPublicActivityDraftTokenRouteImport.update({
    id: '/api/public/activity-draft/$token',
    path: '/api/public/activity-draft/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjetosProjectIdOrganogramaRoute =
  AuthenticatedProjetosProjectIdOrganogramaRouteImport.update({
    id: '/organograma',
    path: '/organograma',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdHistoricoRoute =
  AuthenticatedProjetosProjectIdHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoRouteImport.update({
    id: '/descricao-cargo',
    path: '/descricao-cargo',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdConfiguracoesRoute =
  AuthenticatedProjetosProjectIdConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdColaboradoresRoute =
  AuthenticatedProjetosProjectIdColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdBaseRoute =
  AuthenticatedProjetosProjectIdBaseRouteImport.update({
    id: '/base',
    path: '/base',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute =
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteImport.update({
    id: '/avaliacao-desempenho',
    path: '/avaliacao-desempenho',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAtividadesRoute =
  AuthenticatedProjetosProjectIdAtividadesRouteImport.update({
    id: '/atividades',
    path: '/atividades',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAreasRoute =
  AuthenticatedProjetosProjectIdAreasRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedProjetosProjectIdAndamentoRoute =
  AuthenticatedProjetosProjectIdAndamentoRouteImport.update({
    id: '/andamento',
    path: '/andamento',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)
const AuthenticatedGerenciamentoUsuariosNovoRoute =
  AuthenticatedGerenciamentoUsuariosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedGerenciamentoUsuariosRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjetosProjectIdDescricaoCargoRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProjetosProjectIdDescricaoCargoRoute,
  } as any)
const AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute =
  AuthenticatedProjetosProjectIdDescricaoCargoDcIdRouteImport.update({
    id: '/$dcId',
    path: '/$dcId',
    getParentRoute: () => AuthenticatedProjetosProjectIdDescricaoCargoRoute,
  } as any)
const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute =
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRouteImport.update(
    {
      id: '/comparar/$reviewId',
      path: '/comparar/$reviewId',
      getParentRoute: () =>
        AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/gerenciamento/atrelar': typeof AuthenticatedGerenciamentoAtrelarRoute
  '/gerenciamento/bases': typeof AuthenticatedGerenciamentoBasesRoute
  '/gerenciamento/usuarios': typeof AuthenticatedGerenciamentoUsuariosRouteWithChildren
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRouteWithChildren
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/atividades/preencher/$token': typeof AtividadesPreencherTokenRoute
  '/avaliacao-desempenho/preencher/$token': typeof AvaliacaoDesempenhoPreencherTokenRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/gerenciamento/usuarios/novo': typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  '/projetos/$projectId/andamento': typeof AuthenticatedProjetosProjectIdAndamentoRoute
  '/projetos/$projectId/areas': typeof AuthenticatedProjetosProjectIdAreasRoute
  '/projetos/$projectId/atividades': typeof AuthenticatedProjetosProjectIdAtividadesRoute
  '/projetos/$projectId/avaliacao-desempenho': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  '/projetos/$projectId/base': typeof AuthenticatedProjetosProjectIdBaseRoute
  '/projetos/$projectId/colaboradores': typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  '/projetos/$projectId/configuracoes': typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  '/projetos/$projectId/descricao-cargo': typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren
  '/projetos/$projectId/historico': typeof AuthenticatedProjetosProjectIdHistoricoRoute
  '/projetos/$projectId/organograma': typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  '/api/public/activity-draft/$token': typeof ApiPublicActivityDraftTokenRoute
  '/api/public/activity-form/$token': typeof ApiPublicActivityFormTokenRoute
  '/api/public/activity-response/$token': typeof ApiPublicActivityResponseTokenRoute
  '/api/public/performance-draft/$token': typeof ApiPublicPerformanceDraftTokenRoute
  '/api/public/performance-form/$token': typeof ApiPublicPerformanceFormTokenRoute
  '/api/public/performance-response/$token': typeof ApiPublicPerformanceResponseTokenRoute
  '/gerenciamento/usuarios/': typeof AuthenticatedGerenciamentoUsuariosIndexRoute
  '/projetos/$projectId/': typeof AuthenticatedProjetosProjectIdIndexRoute
  '/projetos/$projectId/descricao-cargo/$dcId': typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  '/projetos/$projectId/descricao-cargo/novo': typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  '/projetos/$projectId/descricao-cargo/': typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
  '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/gerenciamento/atrelar': typeof AuthenticatedGerenciamentoAtrelarRoute
  '/gerenciamento/bases': typeof AuthenticatedGerenciamentoBasesRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/atividades/preencher/$token': typeof AtividadesPreencherTokenRoute
  '/avaliacao-desempenho/preencher/$token': typeof AvaliacaoDesempenhoPreencherTokenRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/gerenciamento/usuarios/novo': typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  '/projetos/$projectId/andamento': typeof AuthenticatedProjetosProjectIdAndamentoRoute
  '/projetos/$projectId/areas': typeof AuthenticatedProjetosProjectIdAreasRoute
  '/projetos/$projectId/atividades': typeof AuthenticatedProjetosProjectIdAtividadesRoute
  '/projetos/$projectId/avaliacao-desempenho': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  '/projetos/$projectId/base': typeof AuthenticatedProjetosProjectIdBaseRoute
  '/projetos/$projectId/colaboradores': typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  '/projetos/$projectId/configuracoes': typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  '/projetos/$projectId/historico': typeof AuthenticatedProjetosProjectIdHistoricoRoute
  '/projetos/$projectId/organograma': typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  '/api/public/activity-draft/$token': typeof ApiPublicActivityDraftTokenRoute
  '/api/public/activity-form/$token': typeof ApiPublicActivityFormTokenRoute
  '/api/public/activity-response/$token': typeof ApiPublicActivityResponseTokenRoute
  '/api/public/performance-draft/$token': typeof ApiPublicPerformanceDraftTokenRoute
  '/api/public/performance-form/$token': typeof ApiPublicPerformanceFormTokenRoute
  '/api/public/performance-response/$token': typeof ApiPublicPerformanceResponseTokenRoute
  '/gerenciamento/usuarios': typeof AuthenticatedGerenciamentoUsuariosIndexRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdIndexRoute
  '/projetos/$projectId/descricao-cargo/$dcId': typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  '/projetos/$projectId/descricao-cargo/novo': typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  '/projetos/$projectId/descricao-cargo': typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
  '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRouteWithChildren
  '/_authenticated/gerenciamento/atrelar': typeof AuthenticatedGerenciamentoAtrelarRoute
  '/_authenticated/gerenciamento/bases': typeof AuthenticatedGerenciamentoBasesRoute
  '/_authenticated/gerenciamento/usuarios': typeof AuthenticatedGerenciamentoUsuariosRouteWithChildren
  '/_authenticated/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRouteWithChildren
  '/_authenticated/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/atividades/preencher/$token': typeof AtividadesPreencherTokenRoute
  '/avaliacao-desempenho/preencher/$token': typeof AvaliacaoDesempenhoPreencherTokenRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/_authenticated/gerenciamento/usuarios/novo': typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  '/_authenticated/projetos/$projectId/andamento': typeof AuthenticatedProjetosProjectIdAndamentoRoute
  '/_authenticated/projetos/$projectId/areas': typeof AuthenticatedProjetosProjectIdAreasRoute
  '/_authenticated/projetos/$projectId/atividades': typeof AuthenticatedProjetosProjectIdAtividadesRoute
  '/_authenticated/projetos/$projectId/avaliacao-desempenho': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  '/_authenticated/projetos/$projectId/base': typeof AuthenticatedProjetosProjectIdBaseRoute
  '/_authenticated/projetos/$projectId/colaboradores': typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  '/_authenticated/projetos/$projectId/configuracoes': typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  '/_authenticated/projetos/$projectId/descricao-cargo': typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren
  '/_authenticated/projetos/$projectId/historico': typeof AuthenticatedProjetosProjectIdHistoricoRoute
  '/_authenticated/projetos/$projectId/organograma': typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  '/api/public/activity-draft/$token': typeof ApiPublicActivityDraftTokenRoute
  '/api/public/activity-form/$token': typeof ApiPublicActivityFormTokenRoute
  '/api/public/activity-response/$token': typeof ApiPublicActivityResponseTokenRoute
  '/api/public/performance-draft/$token': typeof ApiPublicPerformanceDraftTokenRoute
  '/api/public/performance-form/$token': typeof ApiPublicPerformanceFormTokenRoute
  '/api/public/performance-response/$token': typeof ApiPublicPerformanceResponseTokenRoute
  '/_authenticated/gerenciamento/usuarios/': typeof AuthenticatedGerenciamentoUsuariosIndexRoute
  '/_authenticated/projetos/$projectId/': typeof AuthenticatedProjetosProjectIdIndexRoute
  '/_authenticated/projetos/$projectId/descricao-cargo/$dcId': typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  '/_authenticated/projetos/$projectId/descricao-cargo/novo': typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  '/_authenticated/projetos/$projectId/descricao-cargo/': typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
  '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projetos'
    | '/gerenciamento/atrelar'
    | '/gerenciamento/bases'
    | '/gerenciamento/usuarios'
    | '/projetos/$projectId'
    | '/projetos/novo'
    | '/atividades/preencher/$token'
    | '/avaliacao-desempenho/preencher/$token'
    | '/projetos/'
    | '/gerenciamento/usuarios/novo'
    | '/projetos/$projectId/andamento'
    | '/projetos/$projectId/areas'
    | '/projetos/$projectId/atividades'
    | '/projetos/$projectId/avaliacao-desempenho'
    | '/projetos/$projectId/base'
    | '/projetos/$projectId/colaboradores'
    | '/projetos/$projectId/configuracoes'
    | '/projetos/$projectId/descricao-cargo'
    | '/projetos/$projectId/historico'
    | '/projetos/$projectId/organograma'
    | '/api/public/activity-draft/$token'
    | '/api/public/activity-form/$token'
    | '/api/public/activity-response/$token'
    | '/api/public/performance-draft/$token'
    | '/api/public/performance-form/$token'
    | '/api/public/performance-response/$token'
    | '/gerenciamento/usuarios/'
    | '/projetos/$projectId/'
    | '/projetos/$projectId/descricao-cargo/$dcId'
    | '/projetos/$projectId/descricao-cargo/novo'
    | '/projetos/$projectId/descricao-cargo/'
    | '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/gerenciamento/atrelar'
    | '/gerenciamento/bases'
    | '/projetos/novo'
    | '/atividades/preencher/$token'
    | '/avaliacao-desempenho/preencher/$token'
    | '/projetos'
    | '/gerenciamento/usuarios/novo'
    | '/projetos/$projectId/andamento'
    | '/projetos/$projectId/areas'
    | '/projetos/$projectId/atividades'
    | '/projetos/$projectId/avaliacao-desempenho'
    | '/projetos/$projectId/base'
    | '/projetos/$projectId/colaboradores'
    | '/projetos/$projectId/configuracoes'
    | '/projetos/$projectId/historico'
    | '/projetos/$projectId/organograma'
    | '/api/public/activity-draft/$token'
    | '/api/public/activity-form/$token'
    | '/api/public/activity-response/$token'
    | '/api/public/performance-draft/$token'
    | '/api/public/performance-form/$token'
    | '/api/public/performance-response/$token'
    | '/gerenciamento/usuarios'
    | '/projetos/$projectId'
    | '/projetos/$projectId/descricao-cargo/$dcId'
    | '/projetos/$projectId/descricao-cargo/novo'
    | '/projetos/$projectId/descricao-cargo'
    | '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/projetos'
    | '/_authenticated/gerenciamento/atrelar'
    | '/_authenticated/gerenciamento/bases'
    | '/_authenticated/gerenciamento/usuarios'
    | '/_authenticated/projetos/$projectId'
    | '/_authenticated/projetos/novo'
    | '/atividades/preencher/$token'
    | '/avaliacao-desempenho/preencher/$token'
    | '/_authenticated/projetos/'
    | '/_authenticated/gerenciamento/usuarios/novo'
    | '/_authenticated/projetos/$projectId/andamento'
    | '/_authenticated/projetos/$projectId/areas'
    | '/_authenticated/projetos/$projectId/atividades'
    | '/_authenticated/projetos/$projectId/avaliacao-desempenho'
    | '/_authenticated/projetos/$projectId/base'
    | '/_authenticated/projetos/$projectId/colaboradores'
    | '/_authenticated/projetos/$projectId/configuracoes'
    | '/_authenticated/projetos/$projectId/descricao-cargo'
    | '/_authenticated/projetos/$projectId/historico'
    | '/_authenticated/projetos/$projectId/organograma'
    | '/api/public/activity-draft/$token'
    | '/api/public/activity-form/$token'
    | '/api/public/activity-response/$token'
    | '/api/public/performance-draft/$token'
    | '/api/public/performance-form/$token'
    | '/api/public/performance-response/$token'
    | '/_authenticated/gerenciamento/usuarios/'
    | '/_authenticated/projetos/$projectId/'
    | '/_authenticated/projetos/$projectId/descricao-cargo/$dcId'
    | '/_authenticated/projetos/$projectId/descricao-cargo/novo'
    | '/_authenticated/projetos/$projectId/descricao-cargo/'
    | '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AtividadesPreencherTokenRoute: typeof AtividadesPreencherTokenRoute
  AvaliacaoDesempenhoPreencherTokenRoute: typeof AvaliacaoDesempenhoPreencherTokenRoute
  ApiPublicActivityDraftTokenRoute: typeof ApiPublicActivityDraftTokenRoute
  ApiPublicActivityFormTokenRoute: typeof ApiPublicActivityFormTokenRoute
  ApiPublicActivityResponseTokenRoute: typeof ApiPublicActivityResponseTokenRoute
  ApiPublicPerformanceDraftTokenRoute: typeof ApiPublicPerformanceDraftTokenRoute
  ApiPublicPerformanceFormTokenRoute: typeof ApiPublicPerformanceFormTokenRoute
  ApiPublicPerformanceResponseTokenRoute: typeof ApiPublicPerformanceResponseTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/avaliacao-desempenho/preencher/$token': {
      id: '/avaliacao-desempenho/preencher/$token'
      path: '/avaliacao-desempenho/preencher/$token'
      fullPath: '/avaliacao-desempenho/preencher/$token'
      preLoaderRoute: typeof AvaliacaoDesempenhoPreencherTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/preencher/$token': {
      id: '/atividades/preencher/$token'
      path: '/atividades/preencher/$token'
      fullPath: '/atividades/preencher/$token'
      preLoaderRoute: typeof AtividadesPreencherTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/novo': {
      id: '/_authenticated/projetos/novo'
      path: '/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof AuthenticatedProjetosNovoRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/projetos/$projectId': {
      id: '/_authenticated/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjetosRoute
    }
    '/_authenticated/gerenciamento/usuarios': {
      id: '/_authenticated/gerenciamento/usuarios'
      path: '/gerenciamento/usuarios'
      fullPath: '/gerenciamento/usuarios'
      preLoaderRoute: typeof AuthenticatedGerenciamentoUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gerenciamento/bases': {
      id: '/_authenticated/gerenciamento/bases'
      path: '/gerenciamento/bases'
      fullPath: '/gerenciamento/bases'
      preLoaderRoute: typeof AuthenticatedGerenciamentoBasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gerenciamento/atrelar': {
      id: '/_authenticated/gerenciamento/atrelar'
      path: '/gerenciamento/atrelar'
      fullPath: '/gerenciamento/atrelar'
      preLoaderRoute: typeof AuthenticatedGerenciamentoAtrelarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos/$projectId/': {
      id: '/_authenticated/projetos/$projectId/'
      path: '/'
      fullPath: '/projetos/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/gerenciamento/usuarios/': {
      id: '/_authenticated/gerenciamento/usuarios/'
      path: '/'
      fullPath: '/gerenciamento/usuarios/'
      preLoaderRoute: typeof AuthenticatedGerenciamentoUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedGerenciamentoUsuariosRoute
    }
    '/api/public/performance-response/$token': {
      id: '/api/public/performance-response/$token'
      path: '/api/public/performance-response/$token'
      fullPath: '/api/public/performance-response/$token'
      preLoaderRoute: typeof ApiPublicPerformanceResponseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/performance-form/$token': {
      id: '/api/public/performance-form/$token'
      path: '/api/public/performance-form/$token'
      fullPath: '/api/public/performance-form/$token'
      preLoaderRoute: typeof ApiPublicPerformanceFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/performance-draft/$token': {
      id: '/api/public/performance-draft/$token'
      path: '/api/public/performance-draft/$token'
      fullPath: '/api/public/performance-draft/$token'
      preLoaderRoute: typeof ApiPublicPerformanceDraftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activity-response/$token': {
      id: '/api/public/activity-response/$token'
      path: '/api/public/activity-response/$token'
      fullPath: '/api/public/activity-response/$token'
      preLoaderRoute: typeof ApiPublicActivityResponseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activity-form/$token': {
      id: '/api/public/activity-form/$token'
      path: '/api/public/activity-form/$token'
      fullPath: '/api/public/activity-form/$token'
      preLoaderRoute: typeof ApiPublicActivityFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activity-draft/$token': {
      id: '/api/public/activity-draft/$token'
      path: '/api/public/activity-draft/$token'
      fullPath: '/api/public/activity-draft/$token'
      preLoaderRoute: typeof ApiPublicActivityDraftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/$projectId/organograma': {
      id: '/_authenticated/projetos/$projectId/organograma'
      path: '/organograma'
      fullPath: '/projetos/$projectId/organograma'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdOrganogramaRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/historico': {
      id: '/_authenticated/projetos/$projectId/historico'
      path: '/historico'
      fullPath: '/projetos/$projectId/historico'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdHistoricoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo'
      path: '/descricao-cargo'
      fullPath: '/projetos/$projectId/descricao-cargo'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/configuracoes': {
      id: '/_authenticated/projetos/$projectId/configuracoes'
      path: '/configuracoes'
      fullPath: '/projetos/$projectId/configuracoes'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/colaboradores': {
      id: '/_authenticated/projetos/$projectId/colaboradores'
      path: '/colaboradores'
      fullPath: '/projetos/$projectId/colaboradores'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdColaboradoresRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/base': {
      id: '/_authenticated/projetos/$projectId/base'
      path: '/base'
      fullPath: '/projetos/$projectId/base'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdBaseRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/avaliacao-desempenho': {
      id: '/_authenticated/projetos/$projectId/avaliacao-desempenho'
      path: '/avaliacao-desempenho'
      fullPath: '/projetos/$projectId/avaliacao-desempenho'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/atividades': {
      id: '/_authenticated/projetos/$projectId/atividades'
      path: '/atividades'
      fullPath: '/projetos/$projectId/atividades'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAtividadesRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/areas': {
      id: '/_authenticated/projetos/$projectId/areas'
      path: '/areas'
      fullPath: '/projetos/$projectId/areas'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAreasRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/projetos/$projectId/andamento': {
      id: '/_authenticated/projetos/$projectId/andamento'
      path: '/andamento'
      fullPath: '/projetos/$projectId/andamento'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAndamentoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
    '/_authenticated/gerenciamento/usuarios/novo': {
      id: '/_authenticated/gerenciamento/usuarios/novo'
      path: '/novo'
      fullPath: '/gerenciamento/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedGerenciamentoUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedGerenciamentoUsuariosRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo/': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo/'
      path: '/'
      fullPath: '/projetos/$projectId/descricao-cargo/'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo/novo': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo/novo'
      path: '/novo'
      fullPath: '/projetos/$projectId/descricao-cargo/novo'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRoute
    }
    '/_authenticated/projetos/$projectId/descricao-cargo/$dcId': {
      id: '/_authenticated/projetos/$projectId/descricao-cargo/$dcId'
      path: '/$dcId'
      fullPath: '/projetos/$projectId/descricao-cargo/$dcId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRoute
    }
    '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId': {
      id: '/_authenticated/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
      path: '/comparar/$reviewId'
      fullPath: '/projetos/$projectId/avaliacao-desempenho/comparar/$reviewId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute
    }
  }
}

interface AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren {
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute
}

const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren: AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren =
  {
    AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute:
      AuthenticatedProjetosProjectIdAvaliacaoDesempenhoCompararReviewIdRoute,
  }

const AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren =
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute._addFileChildren(
    AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteChildren,
  )

interface AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren {
  AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute
  AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute
  AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute
}

const AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren: AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren =
  {
    AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoDcIdRoute,
    AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoNovoRoute,
    AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoIndexRoute,
  }

const AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren =
  AuthenticatedProjetosProjectIdDescricaoCargoRoute._addFileChildren(
    AuthenticatedProjetosProjectIdDescricaoCargoRouteChildren,
  )

interface AuthenticatedProjetosProjectIdRouteChildren {
  AuthenticatedProjetosProjectIdAndamentoRoute: typeof AuthenticatedProjetosProjectIdAndamentoRoute
  AuthenticatedProjetosProjectIdAreasRoute: typeof AuthenticatedProjetosProjectIdAreasRoute
  AuthenticatedProjetosProjectIdAtividadesRoute: typeof AuthenticatedProjetosProjectIdAtividadesRoute
  AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute: typeof AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren
  AuthenticatedProjetosProjectIdBaseRoute: typeof AuthenticatedProjetosProjectIdBaseRoute
  AuthenticatedProjetosProjectIdColaboradoresRoute: typeof AuthenticatedProjetosProjectIdColaboradoresRoute
  AuthenticatedProjetosProjectIdConfiguracoesRoute: typeof AuthenticatedProjetosProjectIdConfiguracoesRoute
  AuthenticatedProjetosProjectIdDescricaoCargoRoute: typeof AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren
  AuthenticatedProjetosProjectIdHistoricoRoute: typeof AuthenticatedProjetosProjectIdHistoricoRoute
  AuthenticatedProjetosProjectIdOrganogramaRoute: typeof AuthenticatedProjetosProjectIdOrganogramaRoute
  AuthenticatedProjetosProjectIdIndexRoute: typeof AuthenticatedProjetosProjectIdIndexRoute
}

const AuthenticatedProjetosProjectIdRouteChildren: AuthenticatedProjetosProjectIdRouteChildren =
  {
    AuthenticatedProjetosProjectIdAndamentoRoute:
      AuthenticatedProjetosProjectIdAndamentoRoute,
    AuthenticatedProjetosProjectIdAreasRoute:
      AuthenticatedProjetosProjectIdAreasRoute,
    AuthenticatedProjetosProjectIdAtividadesRoute:
      AuthenticatedProjetosProjectIdAtividadesRoute,
    AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRoute:
      AuthenticatedProjetosProjectIdAvaliacaoDesempenhoRouteWithChildren,
    AuthenticatedProjetosProjectIdBaseRoute:
      AuthenticatedProjetosProjectIdBaseRoute,
    AuthenticatedProjetosProjectIdColaboradoresRoute:
      AuthenticatedProjetosProjectIdColaboradoresRoute,
    AuthenticatedProjetosProjectIdConfiguracoesRoute:
      AuthenticatedProjetosProjectIdConfiguracoesRoute,
    AuthenticatedProjetosProjectIdDescricaoCargoRoute:
      AuthenticatedProjetosProjectIdDescricaoCargoRouteWithChildren,
    AuthenticatedProjetosProjectIdHistoricoRoute:
      AuthenticatedProjetosProjectIdHistoricoRoute,
    AuthenticatedProjetosProjectIdOrganogramaRoute:
      AuthenticatedProjetosProjectIdOrganogramaRoute,
    AuthenticatedProjetosProjectIdIndexRoute:
      AuthenticatedProjetosProjectIdIndexRoute,
  }

const AuthenticatedProjetosProjectIdRouteWithChildren =
  AuthenticatedProjetosProjectIdRoute._addFileChildren(
    AuthenticatedProjetosProjectIdRouteChildren,
  )

interface AuthenticatedProjetosRouteChildren {
  AuthenticatedProjetosProjectIdRoute: typeof AuthenticatedProjetosProjectIdRouteWithChildren
  AuthenticatedProjetosNovoRoute: typeof AuthenticatedProjetosNovoRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
}

const AuthenticatedProjetosRouteChildren: AuthenticatedProjetosRouteChildren = {
  AuthenticatedProjetosProjectIdRoute:
    AuthenticatedProjetosProjectIdRouteWithChildren,
  AuthenticatedProjetosNovoRoute: AuthenticatedProjetosNovoRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
}

const AuthenticatedProjetosRouteWithChildren =
  AuthenticatedProjetosRoute._addFileChildren(
    AuthenticatedProjetosRouteChildren,
  )

interface AuthenticatedGerenciamentoUsuariosRouteChildren {
  AuthenticatedGerenciamentoUsuariosNovoRoute: typeof AuthenticatedGerenciamentoUsuariosNovoRoute
  AuthenticatedGerenciamentoUsuariosIndexRoute: typeof AuthenticatedGerenciamentoUsuariosIndexRoute
}

const AuthenticatedGerenciamentoUsuariosRouteChildren: AuthenticatedGerenciamentoUsuariosRouteChildren =
  {
    AuthenticatedGerenciamentoUsuariosNovoRoute:
      AuthenticatedGerenciamentoUsuariosNovoRoute,
    AuthenticatedGerenciamentoUsuariosIndexRoute:
      AuthenticatedGerenciamentoUsuariosIndexRoute,
  }

const AuthenticatedGerenciamentoUsuariosRouteWithChildren =
  AuthenticatedGerenciamentoUsuariosRoute._addFileChildren(
    AuthenticatedGerenciamentoUsuariosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRouteWithChildren
  AuthenticatedGerenciamentoAtrelarRoute: typeof AuthenticatedGerenciamentoAtrelarRoute
  AuthenticatedGerenciamentoBasesRoute: typeof AuthenticatedGerenciamentoBasesRoute
  AuthenticatedGerenciamentoUsuariosRoute: typeof AuthenticatedGerenciamentoUsuariosRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjetosRoute: AuthenticatedProjetosRouteWithChildren,
  AuthenticatedGerenciamentoAtrelarRoute:
    AuthenticatedGerenciamentoAtrelarRoute,
  AuthenticatedGerenciamentoBasesRoute: AuthenticatedGerenciamentoBasesRoute,
  AuthenticatedGerenciamentoUsuariosRoute:
    AuthenticatedGerenciamentoUsuariosRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AtividadesPreencherTokenRoute: AtividadesPreencherTokenRoute,
  AvaliacaoDesempenhoPreencherTokenRoute:
    AvaliacaoDesempenhoPreencherTokenRoute,
  ApiPublicActivityDraftTokenRoute: ApiPublicActivityDraftTokenRoute,
  ApiPublicActivityFormTokenRoute: ApiPublicActivityFormTokenRoute,
  ApiPublicActivityResponseTokenRoute: ApiPublicActivityResponseTokenRoute,
  ApiPublicPerformanceDraftTokenRoute: ApiPublicPerformanceDraftTokenRoute,
  ApiPublicPerformanceFormTokenRoute: ApiPublicPerformanceFormTokenRoute,
  ApiPublicPerformanceResponseTokenRoute:
    ApiPublicPerformanceResponseTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
