UPDATE public.performance_review_configs
SET
  name = COALESCE(NULLIF(name, ''), 'Avaliacao de desempenho'),
  questions_schema = '[
    {"id":"avdp_instrucao","label":"Responda aqui a maior instrucao que o avaliado possui:","type":"select","required":true,"active":true,"options":["Ensino Fundamental Incompleto","Ensino Fundamental Completo","Ensino Medio Incompleto","Ensino Medio Completo","Ensino Tecnico","Ensino Superior Incompleto","Ensino Superior Completo","Pos-graduacao"],"sectionTitle":"Instrucao"},
    {"id":"avdp_experiencia","label":"Responda aqui a experiencia que o avaliado possui, em anos:","type":"select","required":true,"active":true,"options":["Menos de 1 ano","1 ano","2 anos","3 anos","4 anos","5 anos","6 a 9 anos","10 ou mais"],"sectionTitle":"Experiencia"},
    {"id":"avdp_atividade_eficiencia","label":"EFICIENCIA - FAZER DA FORMA CORRETA","type":"select","required":true,"active":true,"options":["Domina o processo/metodo desta atividade a ponto de tambem ensinar alguem a executa-la","Executa o processo/metodo desta atividade sem necessitar de auxilio.","Algumas vezes executa o processo/metodo desta atividade necessitando de auxilio.","Muitas vezes executa o processo/metodo desta atividade necessitando de auxilio.","Sempre executa o processo/metodo desta atividade necessitando de auxilio.","Nao se aplica."],"sectionTitle":"Avaliacao das atividades","dynamicSource":"activities","dynamicRole":"efficiency"},
    {"id":"avdp_atividade_eficacia","label":"EFICACIA - RESULTADO E QUALIDADE","type":"select","required":true,"active":true,"options":["Supero os resultados propostos.","Atinjo os resultados propostos.","Na maioria das vezes, atinjo os resultados propostos.","Na maioria das vezes, NAO atinjo os resultados propostos.","Nao atinjo os resultados propostos.","Nao se aplica."],"sectionTitle":"Avaliacao das atividades","dynamicSource":"activities","dynamicRole":"efficacy"},
    {"id":"avdp_indicador_resultado","label":"Resultado","type":"text","required":false,"active":true,"sectionTitle":"Indicadores","dynamicSource":"indicators","dynamicRole":"result"},
    {"id":"avdp_indicador_alcance","label":"% de Alcance","type":"text","required":false,"active":true,"sectionTitle":"Indicadores","dynamicSource":"indicators","dynamicRole":"reach"},
    {"id":"avdp_indicador_enquadramento","label":"Enquadramento","type":"select","required":false,"active":true,"options":["Supero as metas propostas","Atinjo as metas propostas","Atinjo mais que 80% das metas propostas","Atinjo menos que 80% das metas propostas","Nao atinjo","Nao se aplica."],"sectionTitle":"Indicadores","dynamicSource":"indicators","dynamicRole":"fit"},
    {"id":"avdp_habilidade_cultura","label":"Avaliacao da habilidade","type":"select","required":true,"active":true,"options":["Me destaco ao usar esta habilidade nas minhas atividades, sendo exemplo aos demais.","Utilizo na pratica esta habilidade para garantir bons resultados nas minhas atividades","Preciso melhorar UM POUCO na aplicacao desta habilidade, nas minhas atividades.","Preciso melhorar MUITO na aplicacao desta habilidade, nesta atividade.","Preciso melhorar URGENTEMENTE na aplicacao desta habilidade, nas minhas atividades.","Nao se aplica."],"sectionTitle":"Habilidades da cultura organizacional","dynamicSource":"culture_skills","dynamicRole":"rating"},
    {"id":"avdp_habilidade_cargo","label":"Avaliacao da habilidade","type":"select","required":true,"active":true,"options":["Me destaco ao usar esta habilidade nas minhas atividades, sendo exemplo aos demais.","Utilizo na pratica esta habilidade para garantir bons resultados nas minhas atividades","Preciso melhorar UM POUCO na aplicacao desta habilidade, nas minhas atividades.","Preciso melhorar MUITO na aplicacao desta habilidade, nesta atividade.","Preciso melhorar URGENTEMENTE na aplicacao desta habilidade, nas minhas atividades.","Nao se aplica."],"sectionTitle":"Habilidades especificas do cargo","dynamicSource":"role_skills","dynamicRole":"rating"},
    {"id":"avdp_postura","label":"Avaliacao do comportamento","type":"select","required":true,"active":true,"options":["Demonstro este comportamento no dia a dia, a ponto de me DESTACAR perante os demais colaboradores.","Demonstro este comportamento no dia a dia.","Preciso MELHORAR neste comportamento em POUCAS situacoes.","Preciso MELHORAR neste comportamento em MUITAS situacoes.","Preciso MELHORAR URGENTEMENTE neste comportamento.","Nao se aplica."],"sectionTitle":"Postura e comportamento","dynamicSource":"behavior","dynamicRole":"rating"}
  ]'::jsonb
WHERE COALESCE(review_type, 'experience') = 'performance';
